steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/oceanic-isotope-199421/github-zmad5306-gl-list:$COMMIT_SHA", "-t", "gcr.io/oceanic-isotope-199421/github-zmad5306-gl-list:latest", "--build-arg", "version=0.0.1-SNAPSHOT", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/oceanic-isotope-199421/github-zmad5306-gl-list"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/gl-list-deployment	
  - gl-list=gcr.io/oceanic-isotope-199421/github-zmad5306-gl-list:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dev'