apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-list-deployment
  labels:
    app: gl-list
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-list
  template:
    metadata:
      labels:
        app: gl-list
    spec:
      containers:
      - name: gl-list
        image: gl-list:latest
        ports:
        - containerPort: 8080